name: Release

on:
  push:
    branches:
      - master
      - beta
      - 'feature/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release to npm (feature branch)
        if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/beta' && steps.changesets.outputs.hasChangesets == 'false'
        run: |
          git config --global user.email "github-actions@github.com"  
          git config --global user.name "GitHub Actions"  
          
          git status  
          
          if [[ -n $(git status -s) ]]; then  
            git add .  
            git commit -m "Prepare for feature release [skip ci]"  
          fi  
          
          npm version prerelease --preid=feature-${GITHUB_SHA::8} -m "Bump version to %s [skip ci]"  
          git push --follow-tags  
          npm publish --tag feature
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}