name: Release

on:
  push:
    branches:
      - master
      - beta
      - 'feature/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Enter Beta Mode
        if: github.ref == 'refs/heads/beta' && steps.changesets.outputs.hasChangesets == 'true'
        run: npx changeset pre enter beta

      - name: Exit Beta Mode
        if: github.ref == 'refs/heads/master'
        run: npx changeset pre exit

      - name: Publish Beta
        if: github.ref == 'refs/heads/beta' && steps.changesets.outputs.hasChangesets == 'false'
        run: |
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}